export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const INCREMENT = 'INCREMENT'
export const ADD_SELECT = 'ADD_SELECT'
export const FILTER_BY_SELECT = 'FILTER_BY_SELECT'
export const SET_DATE = 'SET_DATE'
export const FILTER_BY_DATE = 'FILTER_BY_DATE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'
export const ADD_COMMENT = 'ADD_COMMENT'
export const LOAD_ARTICLES = 'LOAD_ARTICLES'


